modules/admin/controllers/DefaultController.php
<?php

namespace app\modules\admin\controllers;

use app\models\MyList;
use Yii;
use yii\web\Controller;

/**
 * Default controller for the `admin` module
 */
class DefaultController extends Controller
{
    public function actionIndex() {
        $one = MyList::getAll();;

        return $this->render('index', [
            'one' => $one,
        ]);
    }

    public function actionCreate() {
        $model = new MyList();

            if ($model->load(Yii::$app->request->post()) && $model->save()) {
                return $this->redirect('index');
            }

            return $this->render('create', ['model' => $model]);
        }

    public function actionEdit($id) {
        $one = MyList::getOne($id);

        if ($one->load(Yii::$app->request->post()) && $one->save()) {
            return $this->redirect('index');
        }

        return $this->render('edit', [
            'one' => $one,
            'id' => $id
        ]);
    }

    public function actionDelete($id) {
        $model = MyList::getOne($id);
        $model->delete();
        return $this->redirect('index');
    }
}

modules/admin/views/default/create.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

?>

<h1>Создать</h1>
<?php $form = ActiveForm::begin(); ?>
<div class="row">
    <div class="col-md-6">
        <?= $form->field($model, 'title')->textInput() ?>
    </div>
    <div class="col-md-6">
        <?= $form->field($model, 'description')->textInput() ?>
    </div>
    <div class="col-md-12">
        <?= Html::submitButton('Create', ['class' => 'btn btn-success']) ?>
    </div>
</div>

<?php ActiveForm::end(); ?>

modules/admin/views/default/edit.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

?>

<h1>Редактировать</h1>
<?php $form = ActiveForm::begin(); ?>
<div class="row">
    <div class="col-md-6">
        <?= $form->field($one, 'title')->textInput() ?>
    </div>
    <div class="col-md-6">
        <?= $form->field($one, 'description')->textInput() ?>
    </div>
    <div class="col-md-12">
        <?= Html::submitButton('Update', ['class' => 'btn btn-success']) ?>
    </div>
</div>
<?php ActiveForm::end(); ?>

modules/admin/views/default/index.php
<?php

use yii\helpers\Url;

?>

<h1>Админка</h1>

<a href="<?= Url::to(['default/create']) ?>" class="btn btn-primary">Create</a>

<table class="table table-stripped">
    <thead>
    <tr>
        <td>#</td>
        <td>Название</td>
        <td>Действие</td>
    </tr>
    </thead>

    <tbody>
    <?php foreach ($one as $item): ?>
        <tr>
            <td><?= $item->id ?></td>
            <td><?= $item->title ?></td>
            <td>
                <a href="<?= Url::to(['default/edit', 'id' => $item->id]) ?>" class="btn btn-success">Редактировать</a>
                <a href="<?= Url::to(['default/delete', 'id' => $item->id]) ?>" class="btn btn-danger">Удалить</a>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>